### ISSUE TITLE
Error 404, View not found [name, type, prefix]: storychief, html, storychiefView 

### ISSUE THREAD

**Issue by ronnyvanderborght** [Story-Chief/joomla-component-storychief#1]
When saving or closing the configuration the component displays a Error 404.

![afbeelding](https://user-images.githubusercontent.com/19472426/49593768-9e2be700-f974-11e8-9546-f47ebc131026.png)

**Comment by gregory-claeyssens** [comment]
Hi @ronnyvanderborght 
Fixed in v1.0.6 by adding a default view to the component, though it doesn't actually do anything
